### ISSUE TITLE
  component: 'el-autocomplete', fetchSuggestions正常使用，triggerOnfocus不生效

### ISSUE THREAD

**Issue by Joe681** [agrass-GitHub/agel-form#1]
fileds.js
`export default function () {
  return {
    data: {},
    items: [
      {
        clearable: true,
        component: 'el-autocomplete',
        prop: 'supplier',
        label: '商品编码',
        /**
         * @param {string} api
         * @param {string} key
         * @description getAncillaryCode 商品编码
         */
        fetchSuggestions: this.$autoCompleteInputFunc(
          'getAncillaryCode',
          'code',
          'productCode'
        ),

        triggerOnfocus: false
      }
    ]
  }
}
`

autoCompleteInputFunc.js
`import * as autoCompleteInputApi from '@/service/api/autoCompleteInput'
/**
 *
 * @param {string} api
 * @param {string} key
 * @returns ElMessageComponent
 */

export const autoCompleteInputFunc = (api, key, field) => {
  const keyName = key
  return async (queryString, cb) => {
    try {
      let result = await autoCompleteInputApi[api]({
        [keyName]: queryString
      })
      // console.log('result',))
      result = result.data.map((v) => ({ value: v[field], id: v.id }))
      console.log('cb', cb)
      cb(result)
    } catch (err) {
      console.error(err)
    }
  }
}
`

**Comment by agrass-GitHub** [comment]
你好，经过测试，该属性正常工作，应该是你大小写写错了，不是 triggerOnfocus，支持驼峰写法和短横线写法，注意大小写间隔规则。
```
  triggerOnFocus: false,
  "trigger-on-focus": false,
```
