### ISSUE TITLE
动态改变表单项的是否必填, 必须要使用自定义表单吗

### ISSUE THREAD

**Issue by suxinwa** [agrass-GitHub/agel-form#11]
![image](https://user-images.githubusercontent.com/37650431/194744496-d006bcb2-dde7-418b-95c0-deb028cfd9c3.png)
![image](https://user-images.githubusercontent.com/37650431/194744505-1d5cca15-063c-4e1e-aabb-39cca6a23c0b.png)

**Comment by agrass-GitHub** [comment]
没太懂你的问题，表单都是数据配置，直接修改对应数据就可。有使用上的问题可加 v

**Comment by suxinwa** [comment]
好的 哥你v多少 我加你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "agrass-GitHub/agel-form"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月12日(星期三) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [agrass-GitHub/agel-form] 动态改变表单项的是否必填, 必须要使用自定义表单吗 (Issue #11)





 
没太懂你的问题，表单都是数据配置，直接修改对于数据就可。有使用上的问题可加 v

**Comment by agrass-GitHub** [comment]
agrass-weixin
