### ISSUE TITLE
怎么使用Form-Item Scoped Slot中 Error插槽?感激不尽

### ISSUE THREAD

**Issue by MaickHao** [agrass-GitHub/agel-form#2]
![微信截图_20211228160540](https://user-images.githubusercontent.com/39757237/147543585-c7f7707d-456a-422d-9446-b466659309ee.png)

error | 自定义表单校验信息的显示方式，参数为 { error }

**Comment by agrass-GitHub** [comment]
经考虑，该功能一般很少使用，暂不考虑支持该插槽。有这个需求的场景，就写 el-form 吧。
