### ISSUE TITLE
怎么使用el-autocompelete中的Autocomplete Scoped Slot

### ISSUE THREAD

**Issue by MaickHao** [agrass-GitHub/agel-form#3]
![微信截图_20211229155649](https://user-images.githubusercontent.com/39757237/147639925-369d0450-06aa-4391-a832-be7c847ce668.png)

这种 Scoped Slot的好像在文档没有看到有实现, 而且这个组件在后台管理系统中使用也较多,可以解决一下嘛?大佬

**Comment by agrass-GitHub** [comment]
item.slots  可以支持组件子插槽，建议看下文档，有介绍。

```js
     {
            prop: "state",
            label: "自动输入",
            component: "el-autocomplete",
            fetchSuggestions: (queryString, cb) => {
              cb([
                { value: "三全鲜食（北新泾店）", address: "长宁区新渔路144号" },
              ]);
            },
            slots: {
              default: ({item}) => {
                return <el-button>{item.address}</el-button>;
              },
            },
          },
```

![image](https://user-images.githubusercontent.com/30621542/147651990-1a756b8a-c127-4fc6-85fd-b6415566f003.png)

**Comment by MaickHao** [comment]
谢谢, 是我的问题, 好久没找到..
感谢大佬..每天都在看着大佬敲form库,跟这大佬学习
