### ISSUE TITLE
el-cascader 组件options是否可以像el-select组件一样支持String，Array[String]，Array[Object]，Promise，Function

### ISSUE THREAD

**Issue by MaickHao** [agrass-GitHub/agel-form#4]
![微信截图_20211230162054](https://user-images.githubusercontent.com/39757237/147734092-76276b7b-29d7-43ad-ac53-13099ee82ddc.png)
大佬.我又来提问题了.

**Comment by agrass-GitHub** [comment]
哇塞，你每天都来阿，不支持，支持的话文档肯定有写的。
