### ISSUE TITLE
0.3.32版本使用vite启动项目报错

### ISSUE THREAD

**Issue by MaickHao** [agrass-GitHub/agel-form#6]
![微信图片_20220107100223](https://user-images.githubusercontent.com/39757237/148479368-e3c2ea79-9ee8-4a8a-9866-70d665e55fa8.png)
老哥..0.3.32版本打包有个小优化的位置..

agel-form/src/index.js路劲下 
第8行import tableditorMenuColumn from "./form/tableditor-menu-column"
建议改成import tableditorMenuColumn from "./form/tableditor-menu-column.vue"
添加一个.vue后缀.
现在使用webpack启动项目没问题.但是用vite启动项目的话,vite不能识别这个.项目会报错..建议添加一下.vue后缀更加方便.

**Comment by agrass-GitHub** [comment]
收到

**Comment by agrass-GitHub** [comment]
还有什么建议，一起提出来，到时一起更新 😀😀

**Comment by MaickHao** [comment]
我也是遇到一个提一个，我把你这个项目用到生产上了，要不加个好友，交流交流

发自我的iPhone

**Comment by agrass-GitHub** [comment]
可以，wx : agrass-weixin 。
